/* Automatically generated by plop buildEntryData action */

import TextTooltip from "./components/text-tooltip/index.js";
import SearchInput from "./components/search-input/index.js";
import ListContainer from "./components/list-container/index.js";
import DeepexiCard from "./components/deepexi-card/index.js";
import LoadingDialog from "./components/loading-dialog/index.js";
import MarkdownView from "./components/markdown-view/index.js";
import LoadingButton from "./components/loading-button/index.js";

// 存储组件列表
const components = [
  TextTooltip,
  SearchInput,
  ListContainer,
  DeepexiCard,
  LoadingDialog,
  MarkdownView,
  LoadingButton
];

// 定义 install 方法，接收 Vue 作为参数。如果使用 use 注册插件，则所有的组件都将被注册
const install = function(Vue) {
  // 判断是否安装
  if (install.installed) return;
  // 遍历注册全局组件
  components.forEach(component => Vue.component(component.name, component));
};

// 判断是否是直接引入文件
if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  // 导出的对象必须具有 install，才能被 Vue.use() 方法安装
  install,
  // 以下是具体的组件列表
  TextTooltip,
  SearchInput,
  ListContainer,
  DeepexiCard,
  LoadingDialog,
  MarkdownView,
  LoadingButton
};
